'use strict';
const $=(s,root=document)=>root.querySelector(s),$$=(s,root=document)=>[...root.querySelectorAll(s)];
const STORAGE='ai-workshop-platform-v3',OLD_STORAGE='ai-workshop-platform-v2';
const INSTRUCTOR_PASSWORD='teacher2026',INSTRUCTOR_SESSION='ai-workshop-instructor-unlocked';
const aMissions=$$('.mission.version-a'),bMissions=$$('.mission.version-b');
let currentView='home',currentIndex=0,seconds=0,timerId=null;

const TOOL_URLS={ChatGPT:'https://chatgpt.com/',NotebookLM:'https://notebooklm.google.com/'};
const A_GUIDES=[
  ['ChatGPT','透過簡單對話確認年級、科目、課次與今日教學目標。',{ChatGPT:'● 使用中｜確認任務',NotebookLM:'○ 稍後使用',Codex:'○ 版本 B 使用'}],
  ['NotebookLM','建立可正常使用的教材來源。',{ChatGPT:'✓ 任務已確認',NotebookLM:'● 使用中｜建立來源',Codex:'○ 版本 B 使用'}],
  ['NotebookLM','找出核心問題、主要重點與教材例子。',{ChatGPT:'✓ 任務已確認',NotebookLM:'● 使用中｜理解教材',Codex:'○ 版本 B 使用'}],
  ['NotebookLM','重組三個教學部分與先後關係。',{ChatGPT:'✓ 任務已確認',NotebookLM:'● 使用中｜重組教學',Codex:'○ 版本 B 使用'}],
  ['ChatGPT','把確認過的內容轉成學生容易理解的語言。',{ChatGPT:'● 使用中｜教學轉譯',NotebookLM:'✓ 分析已完成',Codex:'○ 版本 B 使用'}],
  ['ChatGPT','設計填空心智圖內容與教師答案。',{ChatGPT:'● 使用中｜設計內容',NotebookLM:'✓ 分析已完成',Codex:'○ 版本 B 使用'}],
  ['ChatGPT + 教師','AI 找疑點；教師完成最後判斷。',{ChatGPT:'● 使用中｜找疑點',NotebookLM:'✓ 分析已完成',Codex:'○ 版本 B 使用'}]
];
const A_NEXT=['帶著今日任務卡，切換到 NotebookLM 建立教材來源。','留在 NotebookLM，依來源理解教材。','把已核對重點重組為三個教學部分。','帶著分析結果切換到 ChatGPT 做教學轉譯。','用教師定稿設計填空心智圖內容與答案。','站回教師角色，檢查教材能否真正使用。','查看我的成功樣板，或把方法帶到版本 B。'];

function toolButton(tool){const key=tool.startsWith('ChatGPT')?'ChatGPT':tool,url=TOOL_URLS[key];return url?`<a class="tool-button" href="${url}" target="_blank" rel="noopener noreferrer">開啟 ${key} ↗</a>`:''}
function renderGuides(){aMissions.forEach((mission,i)=>{if(mission.querySelector('.tool-guide'))return;const [tool,purpose,states]=A_GUIDES[i],statuses=Object.entries(states).map(([name,status])=>`<div><strong>${name}</strong><span>${status}</span></div>`).join('');mission.querySelector('.mission-title').insertAdjacentHTML('afterend',`<section class="tool-guide"><div class="tool-guide-main"><span class="label">本關使用工具</span><h3>${tool}</h3><p>${purpose}</p>${toolButton(tool)}</div><div class="tool-status">${statuses}</div></section>`);mission.querySelector('.instructor-only').insertAdjacentHTML('beforebegin',`<section class="next-step"><span>下一步你會做什麼？</span><p>${A_NEXT[i]}</p></section>`)})}
renderGuides();

function getState(){try{return JSON.parse(localStorage.getItem(STORAGE))||{}}catch{return {}}}
function migrate(){if(localStorage.getItem(STORAGE))return;try{const old=JSON.parse(localStorage.getItem(OLD_STORAGE)||'{}');localStorage.setItem(STORAGE,JSON.stringify({missionsA:(old.missions||[]).slice(0,7),missionsB:Array(8).fill(false),tasksA:old.tasks||[],tasksB:[],results:old.results||[],notes:old.notes||{},fields:old.fields||{},mode:old.mode||'learner',view:'home',currentA:Math.min(old.current||0,6),currentB:0,dynamicLessons:{}}))}catch{}}
function activeMissions(){return currentView==='b'?bMissions:aMissions}
function checksFor(version,selector){return $$(`.version-${version.toLowerCase()} ${selector}`)}
function collectState(){return {missionsA:checksFor('A','.mission-check').map(x=>x.checked),missionsB:checksFor('B','.mission-check').map(x=>x.checked),tasksA:checksFor('A','.task-check').map(x=>x.checked),tasksB:checksFor('B','.task-check').map(x=>x.checked),results:$$('.result-check').map(x=>x.checked),notes:Object.fromEntries($$('[data-note]').map(x=>[x.dataset.note,x.value])),fields:Object.fromEntries($$('[data-field]').map(x=>[x.dataset.field,x.value])),dynamicLessons:Object.fromEntries($$('.lesson-result-check').map(x=>[x.dataset.lesson,x.checked])),mode:document.body.classList.contains('instructor-mode')?'instructor':'learner',view:currentView,currentA:currentView==='a'?currentIndex:(getState().currentA||0),currentB:currentView==='b'?currentIndex:(getState().currentB||0)}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(collectState()));updateProgress();renderDynamicLessons()}
function restoreChecks(items,values){items.forEach((x,i)=>x.checked=!!values?.[i])}
function load(){migrate();const s=getState();restoreChecks(checksFor('A','.mission-check'),s.missionsA);restoreChecks(checksFor('B','.mission-check'),s.missionsB);restoreChecks(checksFor('A','.task-check'),s.tasksA);restoreChecks(checksFor('B','.task-check'),s.tasksB);restoreChecks($$('.result-check'),s.results);$$('[data-note]').forEach(x=>x.value=s.notes?.[x.dataset.note]||'');$$('[data-field]').forEach(x=>x.value=s.fields?.[x.dataset.field]||'');setMode(s.mode==='instructor'&&sessionStorage.getItem(INSTRUCTOR_SESSION)==='true'?'instructor':'learner',false);renderDynamicLessons(s.dynamicLessons);showView(s.view||'home',false);updateProgress()}

function versionProgress(version){const checks=checksFor(version,'.mission-check'),done=checks.filter(x=>x.checked).length;return {done,total:checks.length,pct:checks.length?Math.round(done/checks.length*100):0}}
function updateProgress(){const a=versionProgress('A'),b=versionProgress('B'),p=currentView==='b'?b:a;$('#bar').style.width=p.pct+'%';$('#progressText').textContent=p.pct+'%';$('#missionCount').textContent=`${p.done} / ${p.total} 關`;$('.track').setAttribute('aria-valuenow',String(p.pct));$('#homeProgressA').textContent=`完成度 ${a.pct}%（${a.done}/${a.total}）`;$('#homeProgressB').textContent=`完成度 ${b.pct}%（${b.done}/${b.total}）`;const results=$$('.result-check'),done=results.filter(x=>x.checked).length;$('#completionSummary').textContent=`成果驗收：已確認 ${done} / ${results.length} 項。`}
function showView(view,persist=true){currentView=['home','a','b','results'].includes(view)?view:'home';document.body.dataset.view=currentView;$$('[data-view-target]').forEach(x=>x.classList.toggle('active',x.dataset.viewTarget===currentView));if(currentView==='a'||currentView==='b'){const s=getState();currentIndex=currentView==='a'?(s.currentA||0):(s.currentB||0);setCurrent(currentIndex,false)}else{window.scrollTo({top:0,behavior:persist?'smooth':'auto'})}updateProgress();if(persist)save()}
function setCurrent(index,scroll=true){const list=activeMissions();if(!list.length)return;currentIndex=Math.max(0,Math.min(index,list.length-1));const m=list[currentIndex],prefix=currentView.toUpperCase();$('#currentMission').textContent=`${prefix}${currentIndex}｜${m.dataset.title}`;$('#suggestedTime').textContent=`建議 ${m.dataset.time} 分鐘`;$('#stageStatus').textContent=`${prefix}${currentIndex} / ${prefix}${list.length-1}`;$('#prevMission').disabled=currentIndex===0;$('#nextMission').textContent=currentIndex===list.length-1?(currentView==='a'?'查看成功樣板 →':'前往成果 →'):'下一關 →';$$('.mission-nav a').forEach(a=>a.classList.toggle('active',a.hash===`#${m.id}`));if(scroll)m.scrollIntoView({behavior:'smooth',block:'start'});if(currentView==='a'||currentView==='b')save()}

function setMode(mode,persist=true){document.body.classList.toggle('instructor-mode',mode==='instructor');$$('.mode-btn').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));if(persist)save()}
function requestInstructorMode(){if(sessionStorage.getItem(INSTRUCTOR_SESSION)==='true'){setMode('instructor');return}$('#instructorPassword').value='';$('#passwordError').hidden=true;$('#passwordDialog').showModal();setTimeout(()=>$('#instructorPassword').focus(),0)}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.id);toast.id=setTimeout(()=>el.classList.remove('show'),1800)}
function renderDynamicLessons(saved=getState().dynamicLessons||{}){const box=$('#dynamicLessonChecks');if(!box)return;const start=Number($('[data-field="bStart"]').value),end=Number($('[data-field="bEnd"]').value);if(!Number.isInteger(start)||!Number.isInteger(end)||start<0||end<start||end-start>30){box.innerHTML='<p>請先在 B3 輸入有效的起始與結束課次。</p>';return}box.innerHTML=Array.from({length:end-start+1},(_,i)=>{const n=start+i;return `<label><input type="checkbox" class="lesson-result-check" data-lesson="${n}" ${saved[n]?'checked':''}> 第 ${n} 課已確認</label>`}).join('')}

document.addEventListener('input',e=>{if(e.target.matches('input,textarea'))save()});
document.addEventListener('change',e=>{if(!e.target.matches('input[type=checkbox]'))return;save();if(e.target.classList.contains('mission-check')&&e.target.checked){const mission=e.target.closest('.mission'),list=mission.dataset.version==='B'?bMissions:aMissions,index=Number(mission.dataset.mission);toast(`${mission.dataset.version}${index} 已完成`);setTimeout(()=>{if(index<list.length-1)setCurrent(index+1);else if(mission.dataset.version==='A')$('#success-template').scrollIntoView({behavior:'smooth'});else showView('results')},650)}});
$$('[data-view-target]').forEach(x=>x.addEventListener('click',()=>showView(x.dataset.viewTarget)));
$$('.mode-btn').forEach(btn=>btn.addEventListener('click',()=>btn.dataset.mode==='instructor'?requestInstructorMode():setMode('learner')));
$('#passwordForm').addEventListener('submit',e=>{e.preventDefault();const input=$('#instructorPassword');if(input.value!==INSTRUCTOR_PASSWORD){$('#passwordError').hidden=false;input.value='';input.focus();return}sessionStorage.setItem(INSTRUCTOR_SESSION,'true');$('#passwordDialog').close();setMode('instructor');toast('講師模式已開啟')});$('#cancelPassword').addEventListener('click',()=>$('#passwordDialog').close());
$$('.a-nav a[href^="#m"]').forEach(a=>a.addEventListener('click',()=>{currentView='a';setCurrent(Number(a.hash.slice(2)),false)}));$$('.b-nav a[href^="#b"]').forEach(a=>a.addEventListener('click',()=>{currentView='b';setCurrent(Number(a.hash.slice(2)),false)}));
$('#prevMission').addEventListener('click',()=>setCurrent(currentIndex-1));$('#nextMission').addEventListener('click',()=>{const list=activeMissions();if(currentIndex<list.length-1)setCurrent(currentIndex+1);else if(currentView==='a')$('#success-template').scrollIntoView({behavior:'smooth'});else showView('results')});
$$('.copy').forEach(btn=>btn.addEventListener('click',async()=>{const text=$('#'+btn.dataset.target).innerText;try{await navigator.clipboard.writeText(text);toast('Prompt 已複製');const old=btn.textContent;btn.textContent='已複製';setTimeout(()=>btn.textContent=old,1100)}catch{alert('無法自動複製，請手動選取。')}}));
function drawTimer(){const m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');$('#timer').textContent=`${m}:${s}`}$('#timerStart').addEventListener('click',()=>{if(!timerId)timerId=setInterval(()=>{seconds++;drawTimer()},1000)});$('#timerPause').addEventListener('click',()=>{clearInterval(timerId);timerId=null});$('#timerReset').addEventListener('click',()=>{clearInterval(timerId);timerId=null;seconds=0;drawTimer()});
$('#resetAll').addEventListener('click',()=>{if(confirm('確定清除 A／B 兩版進度與筆記？')){localStorage.removeItem(STORAGE);sessionStorage.removeItem(INSTRUCTOR_SESSION);location.reload()}});
function exportMarkdown(){const s=collectState(),a=versionProgress('A'),b=versionProgress('B'),lines=['# AI 輔助教材轉譯｜研習紀錄','',`- 匯出時間：${new Date().toLocaleString('zh-TW')}`,`- 版本 A：${a.done}/${a.total}`,`- 版本 B：${b.done}/${b.total}`,'','## 今日備課任務卡',`- 年級：${s.fields.grade||''}`,`- 科目：${s.fields.subject||''}`,`- 課次：${s.fields.lesson||''}`,`- 目標：${s.notes.learningGoal||''}`,'','## 版本 A 關卡',...aMissions.map((m,i)=>`- [${s.missionsA[i]?'x':' '}] A${i} ${m.dataset.title}`),'','## 三部分知識架構',`- 第一部分：${s.fields.mod1||''}`,s.notes.mod1d||'',`- 第二部分：${s.fields.mod2||''}`,s.notes.mod2d||'',`- 第三部分：${s.fields.mod3||''}`,s.notes.mod3d||'',`- 關係：${s.notes.m3relation||''}`,'','## 版本 B 關卡',...bMissions.map((m,i)=>`- [${s.missionsB[i]?'x':' '}] B${i} ${m.dataset.title}`),`- 處理課次：${s.fields.bStart||''} 至 ${s.fields.bEnd||''}`,'','## 教師筆記'];Object.entries(s.notes).forEach(([k,v])=>{if(v)lines.push(`### ${k}`,v,'')});lines.push('## 批次驗收',...Object.entries(s.dynamicLessons).map(([n,ok])=>`- [${ok?'x':' '}] 第 ${n} 課`));const blob=new Blob([lines.join('\n')],{type:'text/markdown;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='AI教材轉譯雙版本研習紀錄.md';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),500);toast('研習紀錄已匯出')}
$('#exportNotes').addEventListener('click',exportMarkdown);$('#exportNotesBottom').addEventListener('click',exportMarkdown);
const observer=new IntersectionObserver(entries=>{const v=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(v&&v.target.dataset.version?.toLowerCase()===currentView){const i=Number(v.target.dataset.mission);if(i!==currentIndex){currentIndex=i;setCurrent(i,false)}}},{threshold:[.25,.55]});[...aMissions,...bMissions].forEach(m=>observer.observe(m));
load();drawTimer();
